export const API_URL = {
  USERS: '/users',
  ACCOUNTS: '/accounts',
  SUBJECTS: '/subjects',
  COURSES: '/courses',
  COMMENTS: '/comments',
  ANNOUNCEMENTS: '/announcements',
  ASSIGNMENTS: '/assignments',
  ROLES: '/roles',
  UPLOAD: '/uploads',
  SEMESTERS: '/semesters',
  PROJECTS: '/projects',
  GROUPS: '/groups',
  REPORTS: '/reports',
  SCORE_STRUCTURES: '/scorestructures',
  SUBMISSIONS: '/submissions',
  SCORES: '/scores',
  BRIEFS: '/briefs',
};
